export const ErrorCodes = {
  BadRequest: 400,
  Unauthorized: 401,
  PaymentRequired: 402,
  Forbidden: 403,
  NotFound: 404,
  MethodNotAllowed: 405,
  NotAcceptable: 406,
  ProxyAuthenticationRequired: 407,
  RequestTimeout: 408,
  Conflict: 409,
  Gone: 410,
  LengthRequired: 411,
  PreconditionFailed: 412,
  PayloadTooLarge: 413,
  UriTooLong: 414,
  UnsupportedMediaType: 415,
  RangeNotSatisfiable: 416,
  ExpectationFailed: 417,
  ImATeapot: 418,
  MisdirectedRequest: 421,
  UnprocessableEntity: 422,
  Locked: 423,
  FailedDependency: 424,
  TooEarly: 425,
  UpgradeRequired: 426,
  PreconditionRequired: 428,
  TooManyRequests: 429,
  RequestHeaderFieldsTooLarge: 431,
  UnavailableForLegalReasons: 451,
  InternalServerError: 500,
} as const;

export const ErrorMessages = {
  [ErrorCodes.BadRequest]: 'Bad Request',
  [ErrorCodes.Unauthorized]: 'Unauthorized',
  [ErrorCodes.PaymentRequired]: 'Payment Required',
  [ErrorCodes.Forbidden]: 'Forbidden',
  [ErrorCodes.NotFound]: 'Not Found',
  [ErrorCodes.MethodNotAllowed]: 'Method Not Allowed',
  [ErrorCodes.NotAcceptable]: 'Not Acceptable',
  [ErrorCodes.ProxyAuthenticationRequired]: 'Proxy Authentication Required',
  [ErrorCodes.RequestTimeout]: 'Request Timeout',
  [ErrorCodes.Conflict]: 'Conflict',
  [ErrorCodes.Gone]: 'Gone',
  [ErrorCodes.LengthRequired]: 'Length Required',
  [ErrorCodes.PreconditionFailed]: 'Precondition Failed',
  [ErrorCodes.PayloadTooLarge]: 'Payload Too Large',
  [ErrorCodes.UriTooLong]: 'URI Too Long',
  [ErrorCodes.UnsupportedMediaType]: 'Unsupported Media Type',
  [ErrorCodes.RangeNotSatisfiable]: 'Range Not Satisfiable',
  [ErrorCodes.ExpectationFailed]: 'Expectation Failed',
  [ErrorCodes.ImATeapot]: "I'm a teapot",
  [ErrorCodes.MisdirectedRequest]: 'Misdirected Request',
  [ErrorCodes.UnprocessableEntity]: 'Unprocessable Entity',
  [ErrorCodes.Locked]: 'Locked',
  [ErrorCodes.FailedDependency]: 'Failed Dependency',
  [ErrorCodes.TooEarly]: 'Too Early',
  [ErrorCodes.UpgradeRequired]: 'Upgrade Required',
  [ErrorCodes.PreconditionRequired]: 'Precondition Required',
  [ErrorCodes.TooManyRequests]: 'Too Many Requests',
  [ErrorCodes.RequestHeaderFieldsTooLarge]: 'Request Header Fields Too Large',
  [ErrorCodes.UnavailableForLegalReasons]: 'Unavailable For Legal Reasons',
  [ErrorCodes.InternalServerError]: 'Internal Server Error',
} as const;
